// words.js
// Global word bank for Pass the Word (Pasapalabra-style game)
// Each answer begins with its corresponding letter.
// status: 0 = pending, 1 = correct, 2 = wrong

const WORD_BANK = [
  {
    letter: 'A',
    answer: 'ALGEBRA',
    clue: 'Branch of mathematics that uses symbols and letters to represent numbers and operations.',
    status: 0,
  },
  {
    letter: 'B',
    answer: 'BAROQUE',
    clue: 'Ornate and heavily decorated artistic style popular in 17th-century Europe.',
    status: 0,
  },
  {
    letter: 'C',
    answer: 'COMPASS',
    clue: 'Navigational instrument with a magnetic needle that always points north.',
    status: 0,
  },
  {
    letter: 'D',
    answer: 'DROUGHT',
    clue: 'A prolonged period of abnormally low rainfall leading to water shortage.',
    status: 0,
  },
  {
    letter: 'E',
    answer: 'ECLIPSE',
    clue: 'Astronomical event when one celestial body passes through the shadow of another.',
    status: 0,
  },
  {
    letter: 'F',
    answer: 'FJORD',
    clue: 'A long, narrow, deep inlet of the sea between tall cliffs, common in Norway.',
    status: 0,
  },
  {
    letter: 'G',
    answer: 'GLACIER',
    clue: 'A slow-moving mass or river of ice formed from compacted snow on mountains.',
    status: 0,
  },
  {
    letter: 'H',
    answer: 'HIEROGLYPH',
    clue: 'A picture symbol used as a character in the writing system of ancient Egypt.',
    status: 0,
  },
  {
    letter: 'I',
    answer: 'IGLOO',
    clue: 'A dome-shaped shelter built from blocks of compacted snow, used by the Inuit.',
    status: 0,
  },
  {
    letter: 'J',
    answer: 'JAVELIN',
    clue: 'A light spear thrown for distance as a track and field athletic event.',
    status: 0,
  },
  {
    letter: 'K',
    answer: 'KAYAK',
    clue: 'A small, narrow watercraft propelled by a double-bladed paddle.',
    status: 0,
  },
  {
    letter: 'L',
    answer: 'LABYRINTH',
    clue: 'A complicated, irregular network of passages or paths; a maze.',
    status: 0,
  },
  {
    letter: 'M',
    answer: 'MONSOON',
    clue: 'A seasonal prevailing wind that brings heavy rainfall, especially to South Asia.',
    status: 0,
  },
  {
    letter: 'N',
    answer: 'NEBULA',
    clue: 'A giant interstellar cloud of gas and dust visible in outer space.',
    status: 0,
  },
  {
    letter: 'O',
    answer: 'ORBIT',
    clue: 'The curved path a celestial object takes around a star, planet, or moon.',
    status: 0,
  },
  {
    letter: 'P',
    answer: 'PERMAFROST',
    clue: 'Permanently frozen subsoil found beneath the surface in arctic and subarctic regions.',
    status: 0,
  },
  {
    letter: 'Q',
    answer: 'QUARANTINE',
    clue: 'A period of isolation imposed on people or animals to prevent the spread of disease.',
    status: 0,
  },
  {
    letter: 'R',
    answer: 'REFRACTION',
    clue: 'The bending of a light wave as it passes from one transparent medium into another.',
    status: 0,
  },
  {
    letter: 'S',
    answer: 'STALACTITE',
    clue: 'A mineral deposit that hangs like an icicle from the ceiling of a cave.',
    status: 0,
  },
  {
    letter: 'T',
    answer: 'TSUNAMI',
    clue: 'A series of powerful ocean waves generated by an underwater earthquake or landslide.',
    status: 0,
  },
  {
    letter: 'U',
    answer: 'ULTRAVIOLET',
    clue: 'Electromagnetic radiation with wavelengths shorter than visible light, produced by the sun.',
    status: 0,
  },
  {
    letter: 'V',
    answer: 'VENOM',
    clue: 'A toxic substance produced by animals such as snakes, spiders, and jellyfish.',
    status: 0,
  },
  {
    letter: 'W',
    answer: 'WATERSHED',
    clue: 'A ridge or high ground dividing areas drained by different river systems.',
    status: 0,
  },
  {
    letter: 'X',
    answer: 'XYLOPHONE',
    clue: 'A musical instrument consisting of wooden bars of graduated length struck with mallets.',
    status: 0,
  },
  {
    letter: 'Y',
    answer: 'YODEL',
    clue: 'A form of singing that alternates rapidly between chest voice and falsetto head voice.',
    status: 0,
  },
  {
    letter: 'Z',
    answer: 'ZENITH',
    clue: 'The point in the sky or celestial sphere directly above an observer.',
    status: 0,
  },
];
